### PR TITLE
Add support for heartcheck 1.2.2

### PR DESCRIPTION
**Pull request by rafaellima**
<b> Why </b>

Due to a restriction in this `gemspec` it's not possible to update heartcheck to the newest version. 

<b> What </b>

Remove the patch from the requirements params and bump the heartcheck version.

### CODE REVIEW

**Comment by rafaellima** [comment]
c/c @rhruiz

**Comment by rhruiz** [comment]
@rafaellima you will have to do some Gemfile trickery because of rack 2.x requiring ruby 2.2+ just like this [commit](https://github.com/locaweb/heartcheck-redis/commit/c42932af67621d67fd0f21f6a053659d1a78b425) on heartcheck-redis

**Comment by rhruiz** [comment]
@rafaellima , sidekiq has the same problem :(

**Comment by rafaellima** [comment]
@rhruiz it's finally working! thanks 👍

**Pull request merged**
